/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 05:00:12 GMT 2025
 */

package org.apache.commons.lang3.function;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.function.FailableIntPredicate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class FailableIntPredicate_ESTest extends FailableIntPredicate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FailableIntPredicate<Throwable> failableIntPredicate0 = FailableIntPredicate.falsePredicate();
      FailableIntPredicate<Throwable> failableIntPredicate1 = FailableIntPredicate.truePredicate();
      FailableIntPredicate<Throwable> failableIntPredicate2 = failableIntPredicate0.or(failableIntPredicate1);
      assertFalse(failableIntPredicate2.equals((Object)failableIntPredicate1));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FailableIntPredicate<Throwable> failableIntPredicate0 = FailableIntPredicate.falsePredicate();
      FailableIntPredicate<Throwable> failableIntPredicate1 = FailableIntPredicate.truePredicate();
      FailableIntPredicate<Throwable> failableIntPredicate2 = failableIntPredicate0.and(failableIntPredicate1);
      assertFalse(failableIntPredicate2.equals((Object)failableIntPredicate0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FailableIntPredicate<Throwable> failableIntPredicate0 = FailableIntPredicate.falsePredicate();
      FailableIntPredicate<Throwable> failableIntPredicate1 = failableIntPredicate0.and(failableIntPredicate0);
      assertFalse(failableIntPredicate1.equals((Object)failableIntPredicate0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FailableIntPredicate<Throwable> failableIntPredicate0 = FailableIntPredicate.falsePredicate();
      FailableIntPredicate<Throwable> failableIntPredicate1 = failableIntPredicate0.negate();
      assertFalse(failableIntPredicate1.equals((Object)failableIntPredicate0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FailableIntPredicate<Throwable> failableIntPredicate0 = FailableIntPredicate.truePredicate();
      // Undeclared exception!
      try { 
        failableIntPredicate0.or((FailableIntPredicate<Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FailableIntPredicate<Throwable> failableIntPredicate0 = FailableIntPredicate.falsePredicate();
      FailableIntPredicate<Throwable> failableIntPredicate1 = failableIntPredicate0.or(failableIntPredicate0);
      assertFalse(failableIntPredicate1.equals((Object)failableIntPredicate0));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FailableIntPredicate<Throwable> failableIntPredicate0 = FailableIntPredicate.falsePredicate();
      // Undeclared exception!
      try { 
        failableIntPredicate0.and((FailableIntPredicate<Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }
}
