/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 06:01:28 GMT 2025
 */

package org.apache.commons.lang3.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.lang.reflect.UndeclaredThrowableException;
import java.util.LinkedList;
import java.util.List;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.lang.MockError;
import org.evosuite.runtime.mock.java.lang.MockRuntimeException;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ExceptionUtils_ESTest extends ExceptionUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockThrowable mockThrowable0 = new MockThrowable(mockRuntimeException0);
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      MockRuntimeException mockRuntimeException1 = ExceptionUtils.throwableOfThrowable((Throwable) mockThrowable0, class0, (-3521));
      assertSame(mockRuntimeException1, mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<Throwable> class0 = Throwable.class;
      MockRuntimeException mockRuntimeException1 = new MockRuntimeException("3QkbD26^`[RqFfn\"/s", mockRuntimeException0);
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockRuntimeException1, class0, 2);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("Executio of '%q took [%d] ms.");
      LinkedList<String> linkedList1 = new LinkedList<String>(linkedList0);
      linkedList1.add("Executio of '%q took [%d] ms.");
      ExceptionUtils.removeCommonFrames(linkedList0, linkedList1);
      assertEquals(2, linkedList1.size());
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("St!dIo_Std_In");
      LinkedList<String> linkedList1 = new LinkedList<String>(linkedList0);
      ExceptionUtils.removeCommonFrames(linkedList1, linkedList0);
      assertEquals(1, linkedList0.size());
      assertFalse(linkedList0.equals((Object)linkedList1));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("lOMiM9 7=S6/<Zxy@");
      linkedList0.add("lOMiM9 7=S6/<Zxy@");
      ExceptionUtils.removeCommonFrames(linkedList0, linkedList0);
      assertFalse(linkedList0.contains("lOMiM9 7=S6/<Zxy@"));
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException((Throwable) null, "=?");
      Class<Throwable> class0 = Throwable.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) undeclaredThrowableException0, (Class<? extends Throwable>) class0, 3623);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MockError mockError0 = new MockError();
      MockError mockError1 = new MockError(mockError0);
      mockError0.initCause(mockError1);
      String string0 = ExceptionUtils.getRootCauseMessage(mockError0);
      assertEquals("MockError: org.evosuite.runtime.mock.java.lang.MockThrowable", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockError mockError0 = new MockError(":Vg9%l$@)b^BIR6Y");
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockError0, class0, (-340));
      assertSame(throwable0, mockError0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      MockRuntimeException mockRuntimeException0 = ExceptionUtils.throwableOfThrowable((Throwable) mockError0, class0, (-1094));
      assertNull(mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      MockRuntimeException mockRuntimeException1 = ExceptionUtils.throwableOfThrowable((Throwable) mockRuntimeException0, class0);
      assertSame(mockRuntimeException1, mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("");
      Class<Throwable> class0 = Throwable.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, (-2449));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockError0, (Class<? extends Throwable>) class0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      mockRuntimeException0.initCause(mockThrowable0);
      Class<MockThrowable> class0 = MockThrowable.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MockError mockError0 = new MockError("d");
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockError0, (Class<? extends Throwable>) class0, (-796));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MockError mockError0 = new MockError();
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockError0);
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) undeclaredThrowableException0, (Class<? extends Throwable>) class0, (-796));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockThrowable mockThrowable0 = new MockThrowable(mockRuntimeException0);
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockThrowable0, (Class<? extends Throwable>) class0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable(" [wrapped] ");
      Class<Throwable> class0 = Throwable.class;
      boolean boolean0 = ExceptionUtils.hasCause(mockThrowable0, class0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Throwable[] throwableArray0 = ExceptionUtils.getThrowables((Throwable) null);
      assertEquals(0, throwableArray0.length);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      List<Throwable> list0 = ExceptionUtils.getThrowableList((Throwable) null);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      int int0 = ExceptionUtils.getThrowableCount((Throwable) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames("");
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MockError mockError0 = new MockError();
      List<String> list0 = ExceptionUtils.getStackFrameList(mockError0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MockError mockError0 = new MockError();
      StackTraceElement stackTraceElement0 = new StackTraceElement("at", "at", "at", 25);
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[1];
      stackTraceElementArray0[0] = stackTraceElement0;
      mockError0.setStackTrace(stackTraceElementArray0);
      List<String> list0 = ExceptionUtils.getStackFrameList(mockError0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockThrowable0);
        fail("Expecting exception: Throwable");
      
      } catch(Throwable e) {
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockRuntimeException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockError0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add((String) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames(linkedList0, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        ExceptionUtils.printRootCauseStackTrace((Throwable) mockError0, (PrintWriter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // printWriter
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.printRootCauseStackTrace((Throwable) mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MockError mockError0 = new MockError("%vL0:");
      MockThrowable mockThrowable0 = new MockThrowable(mockError0);
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackTrace(mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackFrames(mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackFrames((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MockError mockError0 = new MockError("org.junitpioneer.jupiter.ReportEntryExtension");
      MockThrowable mockThrowable0 = new MockThrowable(mockError0);
      MockError mockError1 = new MockError("org.junitpioneer.jupiter.ReportEntryExtension", mockThrowable0);
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getRootCauseStackTrace(mockError1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockPrintStream mockPrintStream0 = new MockPrintStream(" ");
      ExceptionUtils.printRootCauseStackTrace((Throwable) mockRuntimeException0, (PrintStream) mockPrintStream0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.printRootCauseStackTrace((Throwable) mockRuntimeException0, (PrintStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // printStream
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ExceptionUtils.printRootCauseStackTrace((Throwable) null, (PrintStream) null);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockThrowable mockThrowable0 = new MockThrowable(mockRuntimeException0);
      mockRuntimeException0.initCause(mockThrowable0);
      List<Throwable> list0 = ExceptionUtils.getThrowableList(mockRuntimeException0);
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames("\"Y@Z l;n_-\"");
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Throwable throwable0 = ExceptionUtils.getRootCause((Throwable) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      MockError mockError0 = new MockError();
      Throwable throwable0 = ExceptionUtils.getRootCause(mockError0);
      assertSame(throwable0, mockError0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MockError mockError0 = new MockError(":Vg9%l$@)b^BIR6Y");
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockError0, ":Vg9%l$@)b^BIR6Y");
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException(undeclaredThrowableException0);
      String string0 = ExceptionUtils.getMessage(mockRuntimeException0);
      assertEquals("MockRuntimeException: java.lang.reflect.UndeclaredThrowableException: :Vg9%l$@)b^BIR6Y", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      String string0 = ExceptionUtils.getMessage((Throwable) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      MockError mockError0 = new MockError();
      mockError0.initCause(mockError0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockError0, (String[]) null);
      assertSame(mockError0, throwable0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) null, stringArray0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      MockError mockError0 = new MockError("%vL0:");
      MockThrowable mockThrowable0 = new MockThrowable(mockError0);
      String string0 = ExceptionUtils.getStackTrace(mockThrowable0);
      //  // Unstable assertion: assertEquals("sun.reflect.GeneratedConstructorAccessor122.newInstance(Unknown Source)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("CartesianEnumSource annotation not found");
      Throwable[] throwableArray0 = ExceptionUtils.getThrowables(mockThrowable0);
      assertEquals(1, throwableArray0.length);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) mockError0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) mockRuntimeException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) null);
        fail("Expecting exception: UndeclaredThrowableException");
      
      } catch(UndeclaredThrowableException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<MockThrowable> class0 = MockThrowable.class;
      MockThrowable mockThrowable0 = ExceptionUtils.throwableOfType((Throwable) mockError0, class0);
      assertNull(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      MockError mockError0 = new MockError();
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockError0, (Class<Throwable>) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) null, class0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("St!dIo_Std_In");
      LinkedList<String> linkedList1 = new LinkedList<String>(linkedList0);
      linkedList0.add("$Ti{t(pXff=>Q.U");
      ExceptionUtils.removeCommonFrames(linkedList1, linkedList0);
      assertTrue(linkedList1.contains("St!dIo_Std_In"));
      assertEquals(1, linkedList1.size());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<String> linkedList1 = new LinkedList<String>(linkedList0);
      linkedList1.add("");
      ExceptionUtils.removeCommonFrames(linkedList1, linkedList0);
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames(linkedList0, (List<String>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The List must not be null
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames((List<String>) null, (List<String>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The List must not be null
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      MockFile mockFile0 = new MockFile("MockError: ", "MockError: ");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      ExceptionUtils.printRootCauseStackTrace((Throwable) null, (PrintWriter) mockPrintWriter0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      ExceptionUtils.printRootCauseStackTrace((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<Throwable> class0 = Throwable.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockError0, (Class<? extends Throwable>) class0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, 1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      MockError mockError0 = new MockError();
      int int0 = ExceptionUtils.indexOfType((Throwable) mockError0, (Class<? extends Throwable>) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockThrowable0);
      Class<UndeclaredThrowableException> class0 = UndeclaredThrowableException.class;
      boolean boolean0 = ExceptionUtils.hasCause(undeclaredThrowableException0, class0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames((Throwable) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      MockError mockError0 = new MockError();
      String[] stringArray0 = ExceptionUtils.getStackFrames(mockError0);
      assertEquals(6, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      MockError mockError0 = new MockError();
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[4];
      StackTraceElement stackTraceElement0 = new StackTraceElement("", "", "at", (-2507));
      stackTraceElementArray0[0] = stackTraceElement0;
      stackTraceElementArray0[1] = stackTraceElement0;
      stackTraceElementArray0[2] = stackTraceElementArray0[0];
      StackTraceElement stackTraceElement1 = new StackTraceElement("at", "", "', has a length less than 2", 8);
      stackTraceElementArray0[3] = stackTraceElement1;
      mockError0.setStackTrace(stackTraceElementArray0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(":;B;3^?/OH-9q1Dd}.|");
      ExceptionUtils.printRootCauseStackTrace((Throwable) mockError0, (PrintWriter) mockPrintWriter0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      MockError mockError0 = new MockError("org.junitpioneer.jupiter.ReportEntryExtension");
      MockThrowable mockThrowable0 = new MockThrowable(mockError0);
      MockError mockError1 = new MockError("org.junitpioneer.jupiter.ReportEntryExtension", mockThrowable0);
      String[] stringArray0 = ExceptionUtils.getRootCauseStackTrace(mockError1);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getRootCauseStackTrace((Throwable) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      String string0 = ExceptionUtils.getRootCauseMessage((Throwable) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getDefaultCauseMethodNames();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockRuntimeException mockRuntimeException1 = new MockRuntimeException("]O1", mockRuntimeException0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockRuntimeException1, stringArray0);
      assertNotNull(throwable0);
      assertSame(throwable0, mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      String[] stringArray0 = new String[15];
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockRuntimeException0, stringArray0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      MockError mockError0 = new MockError();
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockError0, (String[]) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) null, (Class<? extends Throwable>) class0, 2);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      MockError mockError0 = new MockError("org.junitpioneer.jupiter.ReportEntryExtension");
      int int0 = ExceptionUtils.getThrowableCount(mockError0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      MockError mockError0 = new MockError();
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockError0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) undeclaredThrowableException0);
      assertSame(mockError0, throwable0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      ExceptionUtils exceptionUtils0 = new ExceptionUtils();
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockError0, class0, 2);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException(mockThrowable0);
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockRuntimeException0);
      Class<MockThrowable> class0 = MockThrowable.class;
      MockThrowable mockThrowable1 = ExceptionUtils.throwableOfType((Throwable) undeclaredThrowableException0, class0);
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable", mockThrowable1.toString());
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfThrowable((Throwable) mockError0, class0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockThrowable0, "y<GqC's[<M7ih!aBYRr");
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) undeclaredThrowableException0);
        fail("Expecting exception: UndeclaredThrowableException");
      
      } catch(UndeclaredThrowableException e) {
      }
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("_8~{{}Tark", (Throwable) null);
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockRuntimeException0, "_8~{{}Tark");
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) undeclaredThrowableException0, (Class<? extends Throwable>) class0, (-1));
      assertEquals(1, int0);
  }
}
