/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 23 20:41:39 GMT 2025
 */

package org.apache.commons.collections4.iterators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Iterator;
import org.apache.commons.collections4.iterators.PushbackIterator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class PushbackIterator_ESTest extends PushbackIterator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      PushbackIterator<Object> pushbackIterator0 = new PushbackIterator<Object>(iterator0);
      pushbackIterator0.pushback(pushbackIterator0);
      Object object0 = pushbackIterator0.next();
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PushbackIterator<PushbackIterator<Object>> pushbackIterator0 = new PushbackIterator<PushbackIterator<Object>>((Iterator<? extends PushbackIterator<Object>>) null);
      // Undeclared exception!
      try { 
        pushbackIterator0.next();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.iterators.PushbackIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PushbackIterator<PushbackIterator<Object>> pushbackIterator0 = new PushbackIterator<PushbackIterator<Object>>((Iterator<? extends PushbackIterator<Object>>) null);
      // Undeclared exception!
      try { 
        pushbackIterator0.hasNext();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.iterators.PushbackIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      PushbackIterator<Integer> pushbackIterator0 = new PushbackIterator<Integer>(iterator0);
      Integer integer0 = new Integer(321);
      pushbackIterator0.pushback(integer0);
      PushbackIterator<Object> pushbackIterator1 = PushbackIterator.pushbackIterator((Iterator<?>) pushbackIterator0);
      Object object0 = pushbackIterator1.next();
      assertEquals(321, object0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(iterator0).next();
      PushbackIterator<Integer> pushbackIterator0 = new PushbackIterator<Integer>(iterator0);
      PushbackIterator<Object> pushbackIterator1 = PushbackIterator.pushbackIterator((Iterator<?>) pushbackIterator0);
      Object object0 = pushbackIterator1.next();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      PushbackIterator<Integer> pushbackIterator0 = new PushbackIterator<Integer>(iterator0);
      Integer integer0 = new Integer(321);
      pushbackIterator0.pushback(integer0);
      PushbackIterator<Integer> pushbackIterator1 = new PushbackIterator<Integer>(pushbackIterator0);
      boolean boolean0 = pushbackIterator1.hasNext();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(iterator0).hasNext();
      PushbackIterator<Integer> pushbackIterator0 = new PushbackIterator<Integer>(iterator0);
      boolean boolean0 = pushbackIterator0.hasNext();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Iterator<PushbackIterator<Object>> iterator0 = (Iterator<PushbackIterator<Object>>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      PushbackIterator<Object> pushbackIterator0 = PushbackIterator.pushbackIterator((Iterator<?>) iterator0);
      assertNotNull(pushbackIterator0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        PushbackIterator.pushbackIterator((Iterator<? extends PushbackIterator<Object>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Iterator must not be null
         //
         verifyException("org.apache.commons.collections4.iterators.PushbackIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PushbackIterator<PushbackIterator<Object>> pushbackIterator0 = new PushbackIterator<PushbackIterator<Object>>((Iterator<? extends PushbackIterator<Object>>) null);
      PushbackIterator<Object> pushbackIterator1 = PushbackIterator.pushbackIterator((Iterator<?>) pushbackIterator0);
      pushbackIterator0.pushback(pushbackIterator1);
      boolean boolean0 = pushbackIterator0.hasNext();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PushbackIterator<Object> pushbackIterator0 = new PushbackIterator<Object>((Iterator<?>) null);
      // Undeclared exception!
      try { 
        pushbackIterator0.pushback((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayDeque", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PushbackIterator<Object> pushbackIterator0 = new PushbackIterator<Object>((Iterator<?>) null);
      // Undeclared exception!
      try { 
        pushbackIterator0.remove();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.iterators.PushbackIterator", e);
      }
  }
}
