/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 23 21:15:47 GMT 2025
 */

package org.apache.commons.lang3.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.lang.reflect.UndeclaredThrowableException;
import java.util.LinkedList;
import java.util.List;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.lang.MockError;
import org.evosuite.runtime.mock.java.lang.MockRuntimeException;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ExceptionUtils_ESTest extends ExceptionUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MockError mockError0 = new MockError();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockError0, class0, 1);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("QKTcD7tRMPq}l");
      LinkedList<String> linkedList1 = new LinkedList<String>(linkedList0);
      linkedList1.add("QKTcD7tRMPq}l");
      ExceptionUtils.removeCommonFrames(linkedList1, linkedList0);
      assertEquals(1, linkedList1.size());
      assertTrue(linkedList0.equals((Object)linkedList1));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, 1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("4iDEgY");
      MockThrowable mockThrowable0 = new MockThrowable((String) null, mockRuntimeException0);
      MockThrowable mockThrowable1 = new MockThrowable(mockThrowable0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("|'2K");
      ExceptionUtils.printRootCauseStackTrace((Throwable) mockThrowable1, (PrintWriter) mockPrintWriter0);
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable", mockThrowable1.getMessage());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockRuntimeException mockRuntimeException1 = new MockRuntimeException(mockRuntimeException0);
      mockRuntimeException0.initCause(mockRuntimeException1);
      String string0 = ExceptionUtils.getRootCauseMessage(mockRuntimeException0);
      assertEquals("MockRuntimeException: org.evosuite.runtime.mock.java.lang.MockThrowable", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockRuntimeException0, class0, 2);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) null, class0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("");
      MockThrowable mockThrowable0 = new MockThrowable("", mockRuntimeException0);
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      MockRuntimeException mockRuntimeException1 = ExceptionUtils.throwableOfThrowable((Throwable) mockThrowable0, class0, (-3518));
      assertSame(mockRuntimeException0, mockRuntimeException1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, (-3096));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<Throwable> class0 = Throwable.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("");
      MockError mockError0 = new MockError("", mockThrowable0);
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockError0, (Class<? extends Throwable>) class0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, (-564));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) null, class0, (-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockThrowable mockThrowable0 = new MockThrowable("", mockRuntimeException0);
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockThrowable0, (Class<? extends Throwable>) class0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Class<Throwable> class0 = Throwable.class;
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException((Throwable) null);
      UndeclaredThrowableException undeclaredThrowableException1 = new UndeclaredThrowableException(undeclaredThrowableException0, "");
      boolean boolean0 = ExceptionUtils.hasCause(undeclaredThrowableException1, class0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Throwable[] throwableArray0 = ExceptionUtils.getThrowables(mockRuntimeException0);
      assertEquals(1, throwableArray0.length);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      List<Throwable> list0 = ExceptionUtils.getThrowableList((Throwable) null);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      int int0 = ExceptionUtils.getThrowableCount((Throwable) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      List<String> list0 = ExceptionUtils.getStackFrameList((Throwable) null);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException((Throwable) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) undeclaredThrowableException0);
        fail("Expecting exception: UndeclaredThrowableException");
      
      } catch(UndeclaredThrowableException e) {
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockThrowable0);
        fail("Expecting exception: Throwable");
      
      } catch(Throwable e) {
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockRuntimeException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add((String) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames(linkedList0, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.printRootCauseStackTrace((Throwable) mockRuntimeException0, (PrintWriter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // printWriter
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.printRootCauseStackTrace((Throwable) mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("");
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackTrace(mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackFrames((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getStackFrameList(mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      mockThrowable0.setOriginForDelegate((StackTraceElement) null);
      // Undeclared exception!
      try { 
        ExceptionUtils.getRootCauseStackTrace(mockThrowable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockFile mockFile0 = new MockFile("aRH##_YETQH0r");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      ExceptionUtils.printRootCauseStackTrace((Throwable) mockRuntimeException0, (PrintStream) mockPrintStream0);
      assertEquals(50L, mockFile0.length());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.printRootCauseStackTrace((Throwable) mockRuntimeException0, (PrintStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // printStream
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MockFile mockFile0 = new MockFile("toj>{wv");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      ExceptionUtils.printRootCauseStackTrace((Throwable) null, (PrintStream) mockPrintStream0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MockError mockError0 = new MockError("ePI{#Z)zrN@Z-");
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException(mockError0);
      mockError0.initCause(mockRuntimeException0);
      List<Throwable> list0 = ExceptionUtils.getThrowableList(mockError0);
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames("%q>sT615[KEOX+");
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockRuntimeException mockRuntimeException1 = new MockRuntimeException(mockRuntimeException0);
      String[] stringArray0 = ExceptionUtils.getRootCauseStackTrace(mockRuntimeException1);
      assertEquals(2, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Throwable throwable0 = ExceptionUtils.getRootCause((Throwable) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Throwable throwable0 = ExceptionUtils.getRootCause(mockRuntimeException0);
      assertSame(mockRuntimeException0, throwable0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      String string0 = ExceptionUtils.getMessage(mockRuntimeException0);
      assertEquals("MockRuntimeException: ", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String string0 = ExceptionUtils.getMessage((Throwable) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockRuntimeException0, (String[]) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      MockError mockError0 = new MockError(" ");
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException(mockError0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockRuntimeException0, (String[]) null);
      assertSame(throwable0, mockError0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      String[] stringArray0 = new String[2];
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) null, stringArray0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("");
      String string0 = ExceptionUtils.getStackTrace(mockThrowable0);
      //  // Unstable assertion: assertEquals("sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Throwable[] throwableArray0 = ExceptionUtils.getThrowables((Throwable) null);
      assertEquals(0, throwableArray0.length);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) null);
        fail("Expecting exception: UndeclaredThrowableException");
      
      } catch(UndeclaredThrowableException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) mockRuntimeException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        ExceptionUtils.wrapAndThrow((Throwable) mockError0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      MockRuntimeException mockRuntimeException1 = ExceptionUtils.throwableOfThrowable((Throwable) mockRuntimeException0, class0);
      assertSame(mockRuntimeException0, mockRuntimeException1);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfThrowable((Throwable) mockRuntimeException0, class0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("TEo[wQPiZ`4qP*tX5");
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockRuntimeException0, class0, (-1829));
      assertSame(throwable0, mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      linkedList1.add("WDM");
      linkedList0.add("a5t");
      ExceptionUtils.removeCommonFrames(linkedList1, linkedList0);
      assertEquals(1, linkedList1.size());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames(linkedList0, (List<String>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The List must not be null
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.removeCommonFrames((List<String>) null, (List<String>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The List must not be null
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      ExceptionUtils.printRootCauseStackTrace((Throwable) null, (PrintWriter) null);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      ExceptionUtils.printRootCauseStackTrace((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<MockError> class0 = MockError.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockRuntimeException0, (Class<? extends Throwable>) class0, 256);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Class<Throwable> class0 = Throwable.class;
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException((Throwable) null);
      boolean boolean0 = ExceptionUtils.hasCause(undeclaredThrowableException0, class0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExceptionUtils.hasCause((Throwable) null, (Class<? extends Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.exception.ExceptionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames((Throwable) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      String[] stringArray0 = ExceptionUtils.getStackFrames(mockRuntimeException0);
      assertEquals(6, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getStackFrames("");
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      StackTraceElement stackTraceElement0 = new StackTraceElement("at", "[\")Il", "TsI435m}OT", (-28));
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[9];
      stackTraceElementArray0[0] = stackTraceElement0;
      stackTraceElementArray0[1] = stackTraceElement0;
      stackTraceElementArray0[2] = stackTraceElement0;
      stackTraceElementArray0[3] = stackTraceElement0;
      stackTraceElementArray0[4] = stackTraceElement0;
      stackTraceElementArray0[5] = stackTraceElement0;
      stackTraceElementArray0[6] = stackTraceElementArray0[2];
      stackTraceElementArray0[7] = stackTraceElement0;
      stackTraceElementArray0[8] = stackTraceElement0;
      mockRuntimeException0.setStackTrace(stackTraceElementArray0);
      List<String> list0 = ExceptionUtils.getStackFrameList(mockRuntimeException0);
      assertEquals(9, list0.size());
      
      ExceptionUtils.removeCommonFrames(list0, list0);
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getRootCauseStackTrace((Throwable) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      String string0 = ExceptionUtils.getRootCauseMessage((Throwable) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("/I&B\u0006.iV>S");
      String[] stringArray0 = new String[8];
      stringArray0[2] = "toString";
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockRuntimeException0, stringArray0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockRuntimeException mockRuntimeException1 = new MockRuntimeException(mockRuntimeException0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockRuntimeException1);
      assertNotNull(throwable0);
      assertSame(throwable0, mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockRuntimeException0);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("\ryVSTz{4", mockThrowable0);
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockRuntimeException0);
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) undeclaredThrowableException0, (Class<? extends Throwable>) class0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      UndeclaredThrowableException undeclaredThrowableException0 = new UndeclaredThrowableException(mockThrowable0, "");
      Class<MockThrowable> class0 = MockThrowable.class;
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) undeclaredThrowableException0, (Class<? extends Throwable>) class0, (-524));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      int int0 = ExceptionUtils.indexOfThrowable((Throwable) mockRuntimeException0, (Class<? extends Throwable>) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      int int0 = ExceptionUtils.getThrowableCount(mockRuntimeException0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      ExceptionUtils exceptionUtils0 = new ExceptionUtils();
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfType((Throwable) mockRuntimeException0, class0);
      assertSame(throwable0, mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      String[] stringArray0 = ExceptionUtils.getDefaultCauseMethodNames();
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockRuntimeException mockRuntimeException1 = new MockRuntimeException("e>j.Vng,w", mockRuntimeException0);
      Throwable throwable0 = ExceptionUtils.getCause((Throwable) mockRuntimeException1, stringArray0);
      assertNotNull(throwable0);
      assertSame(throwable0, mockRuntimeException0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      Throwable throwable0 = ExceptionUtils.throwableOfThrowable((Throwable) mockRuntimeException0, (Class<Throwable>) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      MockError mockError0 = new MockError(" ");
      Class<Throwable> class0 = Throwable.class;
      Throwable throwable0 = ExceptionUtils.throwableOfThrowable((Throwable) mockError0, class0, 36);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        ExceptionUtils.rethrow((Throwable) mockError0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
      }
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockThrowable mockThrowable0 = new MockThrowable("Classpath reso<re [", mockRuntimeException0);
      Class<MockRuntimeException> class0 = MockRuntimeException.class;
      int int0 = ExceptionUtils.indexOfType((Throwable) mockThrowable0, (Class<? extends Throwable>) class0, (-964));
      assertEquals(1, int0);
  }
}
